apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GKEClusterClass
metadata:
  name: gkecluster
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  machineType: n1-standard-2
  numNodes: 3
  zone: us-central1-b
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete
