apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: Network
metadata:
  name: tbs-network
spec:
  name: my-tbs-network
  autoCreateSubnetworks: false
  routingConfig:
    routingMode: REGIONAL
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
