apiVersion: database.azure.crossplane.io/v1alpha3
kind: SQLServerClass
metadata:
  name: sqlservermysql
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  adminLoginName: myadmin
  resourceGroupName: group-westus-1
  location: West US
  sslEnforced: false
  version: "5.6"
  pricingTier:
    tier: Basic
    vcores: 4
    family: Gen5
  storageProfile:
    storageGB: 50
    backupRetentionDays: 7
    geoRedundantBackup: false
  providerRef:
    name: azure-provider
  reclaimPolicy: Delete
