apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GlobalAddress
metadata:
  name: sample-globaladdress
spec:
  name: wordpress-globaladdress
  network: projects/crossplane-playground/global/networks/argo
---
apiVersion: servicenetworking.gcp.crossplane.io/v1alpha3
kind: Connection
metadata:
  name: sample-connection
spec:
  network: projects/crossplane-playground/global/networks/argo
  reservedPeeringRangeRefs:
  - name: wordpress-sample-globaladdress
---
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstanceClass
metadata:
  name: cloudsqlinstancemysql
specTemplate:
  forProvider:
    region: us-central
    settings:
      tier: db-n1-standard-1
      dataDiskSizeGb: 20
      ipConfiguration:
        privateNetwork: projects/crossplane-playground/global/networks/argo