apiVersion: storage.aws.crossplane.io/v1alpha3
kind: S3BucketClass
metadata:
  name: s3bucket
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  versioning: false
  cannedACL: private
  region: us-east-1
  localPermission: ReadWrite
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
