apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstanceClass
metadata:
  name: cloudsqlinstancepostgresql
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-west2
    settings:
      tier: db-n1-standard-4
      dataDiskType: PD_SSD
      dataDiskSizeGb: 50
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete
